name: Run Cosma CLI on push
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Cosma and generate config
      uses: mikeal/npx@master
      with:
        args: @graphlab-fr/cosma
    - name: Safety check
      run: which cosma